# -*- coding: utf-8 -*-
"""dictionary and sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5NuLSD7Gu3L7GKa0jmnwBCw4LfxY5Yu
"""

dict1={'a': 1, 'b': 2}
print(dict1)
dict2={'c': 3, 'd': 4}
print(dict2)
print(dict1.update(dict2))

co= {"state": "tamilnadu","country": "india","year": 1947}
x = co.get("state")
print(x)

co= {"state": "tamilnadu","country": "india","year": 1947}
x = co.pop("year")
print(x)
print(co)


colour= {"blue", "yellow", "pink"}
colour.add("black")
print(colour)

colour= {"blue", "yellow", "pink"}
colour.add("black")
print(colour)

colour.discard("black")
print(colour)

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
z = x.intersection(y)
print(z)

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
z = x.difference(y)
print(z)

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
z = x.union(y)
print(z)

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
z = x | y
print(z)