# -*- coding: utf-8 -*-
"""initialsing vriable and its types.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/171G7CcYOZ5msZy0Oa3-mgp8RT9wtcXAW
"""

f1= 10.2
i1=20
str1='python'
l1=[1,2,4,5]
dic1={a:1,b:2}
s=(1,4,6,7)
bo1= 10>6
comp=1+2j

print (type(f1))
print(type(i1))
print(type(str1))
print(type(l1))
print(type(dic1))
print(type(s))
print(type(bo1))
print(type(comp))