# -*- coding: utf-8 -*-
"""list slicing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12DR2I95IZ-KbcNh03v2S8EaLD_Ae81T8
"""

l1=[1,4,3,8,9,4]
print(l1[1:3])
print(l1[ : 4])
print(l1[ -4: -1])