# -*- coding: utf-8 -*-
"""list operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10aSk6FHbtMp8K_8TuJktsB4aor4ecZAM
"""

l1[2]=5
print(l1)
l1.remove(4)
print(l1)
l1.append(10)
print(l1)