# -*- coding: utf-8 -*-
"""string and slicing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17al8u2vh0YuUgH5JsmXACBz6BAwLgsuo
"""

str1 = "object oriented programming"
x = str1.capitalize()
print (x)

str1 = "object oriented programming"
x = str1.center(40)
print (x)

str1 = "object oriented programming"
print(str1[0:3])
print(str1[:6])
print(str1[3:])
print(str1[-3: ])
print(str1[::4])
print(str1[1:9:3])
print(str1[::-1])