# -*- coding: utf-8 -*-
"""tuple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O6SD9Upcb-3_gQOqMzQ_QdKueDLYuCkA
"""

t1=(2,5,7,8,5)
print(t1[1])
print(t1[0: 4])
print(t1[-4:-1])

t1=(2,5,7,8,5)
t2=(4,3,6,5,4)
print(t1+t2)